# Generated by Django 5.2.6 on 2025-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Defina a ordem de exibição')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
