# Generated by Django 5.2.6 on 2025-09-16 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
